import type { DiscoveryResult } from './types.js';

export interface GeneratedConfig {
  envContent: string;
  composeContent: string | null;
  systemdContent: string | null;
  proxyContent: string | null;
}

export function generateConfig(
  result: DiscoveryResult,
  userInputs: { telegramToken?: string; telegramChatId?: string; geminiApiKey?: string; domain?: string },
): GeneratedConfig {
  const env = { ...result.env };

  if (userInputs.telegramToken) env.TELEGRAM_BOT_TOKEN = userInputs.telegramToken;
  if (userInputs.telegramChatId) env.TELEGRAM_CHAT_ID = userInputs.telegramChatId;
  if (userInputs.geminiApiKey) env.GEMINI_API_KEY = userInputs.geminiApiKey;
  if (userInputs.domain) env.GUARDIAN_DOMAIN = userInputs.domain;

  if (!env.GUARDIAN_DB_PASSWORD) {
    env.GUARDIAN_DB_PASSWORD = generatePassword();
  }
  if (!env.DASHBOARD_TOKEN) {
    env.DASHBOARD_TOKEN = generatePassword();
  }

  const envContent = formatEnvFile(env);
  const composeContent = result.dockerCompose ?? null;
  const systemdContent = result.systemdUnit ?? null;
  const proxyContent = result.proxyConfig ?? null;

  return { envContent, composeContent, systemdContent, proxyContent };
}

function formatEnvFile(env: Record<string, string>): string {
  const sections: Record<string, string[]> = {
    'Server': ['PORT', 'NODE_ENV'],
    'Dashboard': ['DASHBOARD_TOKEN'],
    'Database': ['DATABASE_URL'],
    'Telegram': ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID', 'TELEGRAM_WEBHOOK_SECRET'],
    'AI': ['GEMINI_API_KEY', 'GEMINI_MODEL', 'AI_PROVIDER', 'OLLAMA_URL', 'OLLAMA_MODEL'],
    'SSH': ['HOST_SSH_HOST', 'HOST_SSH_PORT', 'HOST_SSH_USER', 'HOST_SSH_KEY_PATH'],
    'Security': ['TRUSTED_IPS', 'TRUSTED_FINGERPRINTS', 'ABUSE_CONFIDENCE_THRESHOLD'],
    'Threat Intel': ['ABUSEIPDB_API_KEY'],
    'Docker Compose': ['GUARDIAN_DOMAIN', 'GUARDIAN_DB_PASSWORD', 'SSH_KEY_DIR'],
  };

  const lines: string[] = ['# Guardian Blue Team — Auto-generated by Discovery Engine', ''];
  const used = new Set<string>();

  for (const [section, keys] of Object.entries(sections)) {
    const sectionLines: string[] = [];
    for (const key of keys) {
      if (env[key] !== undefined) {
        sectionLines.push(`${key}=${env[key]}`);
        used.add(key);
      }
    }
    if (sectionLines.length > 0) {
      lines.push(`# ─── ${section} ${'─'.repeat(Math.max(0, 60 - section.length))}`);
      lines.push(...sectionLines);
      lines.push('');
    }
  }

  const remaining = Object.entries(env).filter(([k]) => !used.has(k));
  if (remaining.length > 0) {
    lines.push('# ─── Other ─────────────────────────────────────────────────────');
    for (const [k, v] of remaining) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generatePassword(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  for (const byte of bytes) {
    result += chars[byte % chars.length];
  }
  return result;
}
