import { SSHCollector, type SSHTarget } from './ssh-collector.js';
import { logger } from '../utils/logger.js';
import type { RawLogEntry } from './log-collector.js';

export interface RawSystemMetrics {
  serverId: number;
  serverName: string;
  collectedAt: Date;
  kernelErrors: Array<{ timestamp: string; message: string }>;
  journalErrors: Array<{ timestamp: string; message: string }>;
  failedUnits: string[];
}

export class SystemCollector {
  static async collect(target: SSHTarget): Promise<RawSystemMetrics | null> {
    const result = await SSHCollector.run(target, [
      'dmesg --time-format iso 2>/dev/null | tail -n 30',
      'echo "---SSEP---"',
      "journalctl -p err --since '5 min ago' --no-pager -o short-iso 2>/dev/null | tail -n 20",
      'echo "---SSEP---"',
      'systemctl list-units --failed --no-legend --no-pager 2>/dev/null',
    ].join(' && '), 15_000);

    if (!result.success) {
      logger.debug({ server: target.name }, 'System collection failed');
      return null;
    }

    try {
      return this.parse(target, result.stdout);
    } catch (err) {
      logger.debug({ server: target.name, err }, 'System parsing failed');
      return null;
    }
  }

  private static parse(target: SSHTarget, stdout: string): RawSystemMetrics {
    const sections = stdout.split('---SSEP---').map(s => s.trim());

    const kernelErrors = this.parseTimestampedLines(sections[0]);
    // Filter SSH multiplexing noise generated by Guardian's own collectors
    const journalErrors = this.parseTimestampedLines(sections[1])
      .filter(e => !e.message.includes('no more sessions') && !e.message.includes('error: channel'));

    const failedUnits = (sections[2] ?? '')
      .split('\n')
      .map(l => l.trim())
      .filter(l => l.length > 0)
      .map(line => {
        // Match a .service unit name, skipping the leading ● bullet
        const match = line.match(/([a-zA-Z0-9@._\-]+\.service)/);
        return match ? match[1] : null;
      })
      .filter((u): u is string => u !== null);

    return {
      serverId: target.id,
      serverName: target.name,
      collectedAt: new Date(),
      kernelErrors,
      journalErrors,
      failedUnits,
    };
  }

  // Returns kernel and journal errors as RawLogEntry[] for the normalizer pipeline.
  static async collectAsRawEntries(target: SSHTarget): Promise<RawLogEntry[]> {
    const metrics = await this.collect(target);
    if (!metrics) return [];
    const entries: RawLogEntry[] = [];
    for (const e of metrics.kernelErrors) {
      entries.push({
        serverId: target.id,
        serverName: target.name,
        source: 'kernel',
        timestamp: new Date(e.timestamp),
        line: e.message,
      });
    }
    for (const e of metrics.journalErrors) {
      entries.push({
        serverId: target.id,
        serverName: target.name,
        source: 'journal_error',
        timestamp: new Date(e.timestamp),
        line: e.message,
      });
    }
    for (const unit of metrics.failedUnits) {
      entries.push({
        serverId: target.id,
        serverName: target.name,
        source: 'systemd_failed',
        timestamp: metrics.collectedAt,
        line: unit,
      });
    }
    return entries;
  }

  private static parseTimestampedLines(section: string): Array<{ timestamp: string; message: string }> {
    if (!section) return [];
    return section
      .split('\n')
      .filter(l => l.trim().length > 0)
      .map(line => {
        const isoMatch = line.match(/^(\d{4}-\d{2}-\d{2}T[\d:.+\-Z]+)\s+(.+)/);
        if (isoMatch) {
          return { timestamp: isoMatch[1], message: isoMatch[2] };
        }
        const shortMatch = line.match(/^(\w{3}\s+\d+\s+[\d:]+)\s+\S+\s+(.+)/);
        if (shortMatch) {
          return { timestamp: shortMatch[1], message: shortMatch[2] };
        }
        return { timestamp: new Date().toISOString(), message: line };
      });
  }
}
